// <auto-generated />
using MS.CQRS.Demo.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MS.CQRS.Demo.Infrastructure.Migrations
{
    [DbContext(typeof(CandidateContext))]
    partial class CandidateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MS.CQRS.Demo.Domain.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Candidate","candidate");
                });

            modelBuilder.Entity("MS.CQRS.Demo.Domain.CandidateAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("StateName")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.ToTable("CandidateAddress","candidate");
                });

            modelBuilder.Entity("MS.CQRS.Demo.Domain.CandidateContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("CandidateContacts","candidate");
                });

            modelBuilder.Entity("MS.CQRS.Demo.Domain.CandidateSkillXref", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkillXref","candidate");
                });

            modelBuilder.Entity("MS.CQRS.Demo.Domain.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Skills","candidate");
                });

            modelBuilder.Entity("MS.CQRS.Demo.Domain.CandidateAddress", b =>
                {
                    b.HasOne("MS.CQRS.Demo.Domain.Candidate", "Candidate")
                        .WithOne("CandidateAddress")
                        .HasForeignKey("MS.CQRS.Demo.Domain.CandidateAddress", "CandidateId")
                        .HasConstraintName("Candidate_FK_CandidateAddress_CandidateID")
                        .IsRequired();
                });

            modelBuilder.Entity("MS.CQRS.Demo.Domain.CandidateContact", b =>
                {
                    b.HasOne("MS.CQRS.Demo.Domain.Candidate", "Candidate")
                        .WithMany("CandidateContacts")
                        .HasForeignKey("CandidateId")
                        .HasConstraintName("Candidate_FK_CandidateContact_CandidateId")
                        .IsRequired();
                });

            modelBuilder.Entity("MS.CQRS.Demo.Domain.CandidateSkillXref", b =>
                {
                    b.HasOne("MS.CQRS.Demo.Domain.Candidate", "Candidate")
                        .WithMany("CandidateSkillXrefs")
                        .HasForeignKey("CandidateId")
                        .IsRequired();

                    b.HasOne("MS.CQRS.Demo.Domain.Skill", "Skill")
                        .WithMany("CandidateSkillXrefs")
                        .HasForeignKey("SkillId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
